APP_NAME=Laravel
APP_ENV=local
APP_KEY=base64:lb/zLwbSorcVzv6wi9fsRbJ1PAnDrCWim0W5mNyRjQo=
APP_DEBUG=true
APP_URL=http://localhost

APP_LOCALE=en
APP_FALLBACK_LOCALE=en
APP_FAKER_LOCALE=en_US

APP_MAINTENANCE_DRIVER=file
# APP_MAINTENANCE_STORE=database

# PHP_CLI_SERVER_WORKERS=4

BCRYPT_ROUNDS=12

LOG_CHANNEL=stack
LOG_STACK=single
LOG_DEPRECATIONS_CHANNEL=null
LOG_LEVEL=debug

DB_CONNECTION=mysql
DB_HOST=127.0.0.1
DB_PORT=3306
DB_DATABASE=e-database
DB_USERNAME=root
DB_PASSWORD= 

SESSION_DRIVER=database
SESSION_LIFETIME=120
SESSION_ENCRYPT=false
SESSION_PATH=/
SESSION_DOMAIN=null

BROADCAST_CONNECTION=log
FILESYSTEM_DISK=local
QUEUE_CONNECTION=database

CACHE_STORE=database
# CACHE_PREFIX=

MEMCACHED_HOST=127.0.0.1

REDIS_CLIENT=phpredis
REDIS_HOST=127.0.0.1
REDIS_PASSWORD=null
REDIS_PORT=6379

MAIL_MAILER=smtp
MAIL_HOST=smtp.gmail.com
MAIL_PORT=587
MAIL_USERNAME=laxmanpradhan784@gmail.com
MAIL_PASSWORD=zhxphfchyqjqmxex
MAIL_ENCRYPTION=tls
MAIL_FROM_ADDRESS=laxmanpradhan784@gmail.com
MAIL_FROM_NAME="PNN Operations"


AWS_ACCESS_KEY_ID=
AWS_SECRET_ACCESS_KEY=
AWS_DEFAULT_REGION=us-east-1
AWS_BUCKET=
AWS_USE_PATH_STYLE_ENDPOINT=false

VITE_APP_NAME="${APP_NAME}"


GOOGLE_CLIENT_ID=38312226508-i5er6upc6e9q9lrb5h3ioq577juk47kl.apps.googleusercontent.com
GOOGLE_CLIENT_SECRET=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
GOOGLE_REDIRECT=http://localhost/e-commmerce/public/auth/google/callback

RAZORPAY_KEY=38312226508-i5er6upc6e9q9lrb5h3ioq577juk47kl.apps.googleusercontent.com
RAZORPAY_SECRET=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

